version: '3.4'

services:
  sample.web.host:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
    - sample.db.host
    
  # sql server
  sample.db.host:
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Password123
    ports:
    - "1433"


